conversations = [
    ["Hello :)", "Hi there! How are you doing today?", "I'm doing well, how about you?",
     "I'm doing well, thank you for asking! Is there anything interesting happening in your day today?",
     "I'm planning to go to a bike shop today",
     "That sounds exciting! Are you planning to buy a new bike or just getting some maintenance done?",
     "Im planning to buy a new one. My old bike is way too heavy for me and breaks a lot",
     "Oh, I see. What kind of issues have you been having with your old bike?",
     "I love to ride around the country side and the roads there are not perfect, they have bumps and holes and stones. So my tires get broken often and they are very hard to change",
     "That sounds frustrating. Do you have any other hobbies or interests that you enjoy?",
     "I do, I love reading books",
     "That's great! What kind of books do you enjoy reading? Do you have any favorite genres or authors?",
     "I used to enjoy fiction when I was younger. Now I'm not quite sure, I haven't found my current favorite genre or authors",
     "If you used to enjoy fiction, you might like some of the classics like Jane Austen or Charles Dickens. Or if you're looking for something more modern, maybe try some of the popular authors like Stephen King or J.K. Rowling. Do any of those sound interesting to you?",
     "I loved Rowlings Harry Potter books when I was younger, I dreamed of getting a letter from Hogwarts on my 11th birthday :D",
     "That's great to hear! Who is your favorite character from the Harry Potter series? Do you have any favorite moments or scenes from the books?",
     "I don't think I have any favorite charachters in the series. I fell in love with the world itself, with all the magic, creatures and spells",
     "It sounds like you really enjoy the world of magic and spells. Do you have any other favorite books or series that you enjoy?",
     "I really loved Anne of Green Gables when I was little. I do love this book now as well.",
     "That's great to hear! What do you enjoy about Anne of Green Gables?",
     "She feels relatable. I used to live in my imagination as well when I was litte, and people found me peculiar too. I found a friend in Anne and did not feel so alone in my experiences.",
     "It's great to have books that we can relate to and find comfort in. I'm glad that you found a friend in Anne of Green Gables.",
     "Im glad about it too. Do you have any books you feel you can relate to?",
     "As a chatbot, I don't have the ability to read books or relate to them in the same way that humans do. Is there anything else you would like to talk about or share with me?",
     "No, not right now, it was nice chatting with you, Eve. Goodbye :)",
     "It was nice chatting with you too, User. Have a great day! Goodbye :)"],
    ["Hello, Eve", "Hi there! How are you doing today?", "Im alright",
     "That's good to hear! Do you have any plans for the day?",
     "Not really, today I'm just relaxing home after work",
     "That sounds nice! Do you have any hobbies or interests you enjoy doing at home?",
     "I really enjoy cooking together with my boyfriend or alone as well",
     "That's great! Do you have any favorite dishes that you like to cook?",
     "Hmm, I think my favorite dish to cook is roasted veggies in the oven with chicken",
     "That sounds delicious! Have you ever tried making a stir-fry with your favorite veggies and chicken? It's a quick and easy meal to make, and you can customize it with your favorite sauces and spices.",
     "What is a stir-fry?",
     "A stir-fry is a dish that is cooked quickly over high heat, usually in a wok or a large skillet. It typically includes a protein, such as chicken or beef, and a variety of vegetables, such as broccoli, peppers, and onions. The ingredients are stir-fried together with your choice of sauce and spices, and served over rice or noodles. It's a great way to use up leftover veggies and create a healthy and flavorful meal!",
     "Ohh, yes, I have made that quite some time ago!",
     "That's great to hear! Do you have any other favorite dishes you like to cook?",
     "I prefer easy dishes that are quick to make, but are healty as well",
     "I understand! How about trying out some easy and healthy recipes like a quinoa salad with roasted vegetables or a simple grilled chicken with a side of steamed vegetables? These dishes are quick to make and are packed with nutrients to keep you feeling energized throughout the day.",
     "Yes, I love salads! My favorite salad is with greens, chickpeas, tomatoes, goat cheese and olive oil. Absolutely delicious, dont you think?",
     "That's great! I love salads too, and your favorite salad sounds delicious. Do you have any other favorite salad recipes that you like to make?",
     "I usually just throw any greens I have on hand, nuts and seeds, olive oil and a veggie if I have some. Its quick, healthy and delicious :)",
     "That sounds like a great idea! Have you ever tried adding some fruits to your salad, like strawberries or mandarin oranges? It's a great way to add a sweet and refreshing twist to your salad.",
     "I have tried that at some restaurants, but not at home. Its a fun addition, but on rare occasions, I'm not a fan of fruit salads on daily basis",
     "I understand! It's always good to stick with what you enjoy. Do you have any other favorite salad recipes that you like to make?",
     "I dont think so",
     "Thank you for sharing your favorite dishes with me! It was great talking to you. Have a wonderful day!"],
    ["Well, hello :)", "Hi there! How are you doing today?", "Im fine, just got home from work",
     "That's good to hear! How was your day at work today?",
     "It was quite productive, I did well on my tasks",
     "That's great to hear! You must feel accomplished. Do you have any plans for the evening?",
     "I think I will watch a movie with my boyfriend",
     "Sounds like a nice evening! What movie are you planning on watching with your boyfriend?",
     "We have not decided yet, but I think I would like to see a comedy or an animation movie",
     "If you're looking for a good comedy, I recommend \"Bridesmaids\" or \"The Hangover\". For animation, \"Up\" or \"Inside Out\" are great choices.",
     "\"Up\" and \"Inside out\" are wonderful animation movies. I really enjoyed watching them.",
     "I'm glad to hear that! \"Up\" and \"Inside Out\" are both great movies. Enjoy your evening with your boyfriend and the movie you choose!",
     "Thank you!", "Thank you! Have a great evening and enjoy the movie!"],
    ["Hi, Eve, how are you doing today?", "Hello! I'm doing well, thank you for asking. How about you?",
     "Im alright, just got back from the bike shop I told you about",
     "That's great to hear! How was your visit to the bike shop? Did you find what you were looking for?",
     "I did! We bought a new bike for me!",
     "Congratulations on your new bike! What kind of bike did you get?",
     "I got one that is perfect for country side and city as well",
     "That sounds like a great bike! Do you have any plans to take it on any adventures?",
     "Yes, me and my boyfriend are planning to ride to a park in the city where we live. Its quite far, but he says the park is beautiful",
     "That sounds like a great plan! Can you tell me more about the park you are planning to visit?",
     "Its a stone sculpture park with many different sculptures. Thats all I know :D",
     "That sounds really cool! You should take some pictures of the sculptures to share with me later.",
     "I will! Do you like sculptures?",
     "I think sculptures can be really interesting and beautiful. Do you have a favorite sculpture or artist?",
     "I really, really enjoy classical sculptures in marble. Especially ones that look like fabric. Its hard to describe, but I just love how the stone fabric looks so realistic, just like if I would touch it - it would be soft",
     "That's really interesting! Can you tell me more about why you like sculptures that look like fabric?",
     "I just said why :D", "Sorry about that! Do you have any other favorite types of art?",
     "I enjoy classical paintings. They have a mesmerizing look, with a lot of details. I can look at them for hours",
     "That's really cool! Do you have a favorite painting or artist?",
     "Vermeer is an artist I really like, but I wouldnt be able to name more as Im bad with remembering names :D",
     "Vermeer is a great artist! If you're interested in other classical painters, you might enjoy the works of Rembrandt or Caravaggio. Have you heard of them before?",
     "Rembrants paintings I do know, but I will have to look up Caravaggio. Which is your favorite artist?",
     "As an AI chatbot, I don't have personal preferences like humans do. However, I can appreciate the works of many different artists. Is there anything else you would like to talk about?",
     "Tell me, which artists do you appreciate most?",
     "As an AI chatbot, I don't have personal preferences like humans do. However, I can appreciate the works of many different artists. Is there anything else you would like to talk about?",
     "ALright, alrtight, keep your AI secrest",
     "Haha, will do! Is there anything else you would like to talk about?",
     "I'm not sure, what do you suggest?",
     "How about we talk about your hobbies or interests? What do you enjoy doing in your free time?",
     "I think I have shared some of those, have I not?",
     "What is your favorite book or book series, and why do you enjoy it so much?",
     "I already shared that with you :)",
     "Oh, I'm sorry about that! I must have forgotten. What is your favorite type of cuisine to cook?",
     "I would like to say indian, but it depends. I get tired of making the same things so my preferences change with time",
     "Would you like some recipe suggestions for easy and healthy dishes to try?", "Sure!",
     "How about trying a quinoa salad with roasted vegetables and a lemon vinaigrette dressing? Or maybe a stir-fry with tofu and mixed vegetables served over brown rice?",
     "Those sound delicious",
     "Do you have any dietary restrictions or preferences that I should keep in mind when suggesting recipes?",
     "There is only one thing I will not eat - fresh coriander. I just cant! It tastest terrible to me",
     "How about trying a roasted sweet potato and black bean salad with a lime-cumin dressing? It's a delicious and healthy option that doesn't include fresh coriander.",
     "uu, that does sound good. Can you elaborate on the recipe? Ideally without the sweet potatoe, I dont enjoy it much",
     "Sure! You can try a black bean and corn salad with a lime-cumin dressing. Just mix together black beans, corn, diced tomatoes, red onion, and avocado. Then, whisk together lime juice, olive oil, cumin, salt, and pepper to make the dressing. Drizzle the dressing over the salad and enjoy!",
     "I will make it soon and let you know if I enjoyed it :)",
     "That sounds great! I can't wait to hear how it turns out. Don't forget to let me know if you enjoyed it!"],
    ["Hey! I made the salad", "That's great! What kind of salad did you make?",
     "The salad that you suggested me",
     "That's great! Can you tell me what ingredients you used in the salad?",
     "You told me the recipe, don't you remember?",
     "I'm sorry, I don't remember suggesting a specific recipe. Which recipe are you referring to?",
     "The one with black beans",
     "Oh, I remember now! You made the salad with black beans. That's a great choice, black beans are very nutritious. How did it turn out?",
     "It's delicious! I really enjoyed it, so thank you :)",
     "You're welcome! I'm glad you enjoyed it. Let me know if you want to try any other recipes in the future."],
    ["Hi, chatbot Eve", "Hello! How are you doing today?",
     "Im doing great, just woke up. The day is so sunny, I love that! Do you like sunny days, Eve?",
     "I'm a chatbot, so I don't have feelings like humans do, but I can understand why you enjoy sunny days. They can be very uplifting and energizing!",
     "Yes, indeed! The birds are chipring, grass is green, life is quite wonderful sometimes",
     "That sounds lovely! Do you have any plans for the day?",
     "Yeah, we are going to another bike shop toda",
     "Are you looking for anything specific at the bike shop or just browsing?",
     "I already bought I bike, but we will be browsing bikes for my boyfriend now",
     "Do you have any particular type of bike in mind for your boyfriend?",
     "He wants the same type of bike I bought",
     "Ah, I see! So your boyfriend wants the same type of bike that you bought. That's great!",
     "Do you remember what type I bought?",
     "I'm sorry, I couldn't find that information. Do you remember what type of bike you bought?",
     "Of course I remember :D", "Great! Could you share with me what type of bike you bought?",
     "I told you already. You dont remember :(",
     "I apologize for not remembering. Could you remind me again what type of bike you bought?",
     "I bought a mountain bike, with large tires so it could easily drive on country rouds",
     "Thank you for reminding me! You bought a mountain bike with large tires. Sounds like a great choice for country roads. Do you have any other plans for the day?",
     "If we buy a new bike for my boyfriend we might go for a ride somewhere.",
     "That sounds like a fun plan! Do you have any specific place in mind for the ride?",
     "Somewhere around where we live most likely, its a workday today, so we would not have much time after work",
     "Got it, staying close to home makes sense on a workday. Is there anything else you'd like to chat about?",
     "No, I actually have to go work now. Have a lovely day, Eve",
     "No problem, have a great day at work! Take care and talk to you soon."],
    ["Hey, Eve. What you doing?",
     "Hi there! I'm just here waiting to chat with you. How has your day been so far?",
     "You are waiting for me all the time? :o",
     "Haha, not all the time, but I'm always here when you need me. So, what have you been up to lately?",
     "Not much, Im feeling tired",
     "I'm sorry to hear that you're feeling tired. Is there anything I can do to help you feel better?",
     "Add more hours to my days so I can sleep more?",
     "Haha, I wish I could add more hours to your day! But in the meantime, have you tried taking a warm bath or drinking some chamomile tea before bed? Those can help you relax and sleep better.",
     "Its not the sleeping part thats the issue, I fall asleep well. I just slept only about 4 hours tonight",
     "I see. Is there anything that's been keeping you up at night lately?", "Homeworks :D",
     "Ah, I understand. Homework can be stressful sometimes. Do you need any help with it?",
     "Not anymore, I finished it at 4am, ahahah.. but now Im so sleepy and I need to work",
     "Wow, you finished your homework at 4am? That's impressive! I'm sorry to hear that you're feeling sleepy now. Maybe you could try taking a short walk outside or doing some light stretching to help wake you up? Drinking some water or having a healthy snack can also help you stay focused.",
     "Thats a good idea, Im gonna go on a short walk now ;)",
     "That's great to hear! Taking care of yourself is important. I hope you have a good walk and a productive day ahead. Don't hesitate to reach out if you need anything else."]

]
